DATASET:
  NAME: MPIIGaze
  DATASET_PATH: data/MPIIGaze_processed/MPIIGaze.h5

EXPERIMENT:
  TEST_ID: 0          # 留出第0号参与者（p00）做测试
  SEED: 42            # 随机种子
  ROOT_DIR: experiments/mpiigaze_transformer
  OUTPUT_DIR: null    # 若为 null，将默认保存在 ROOT_DIR 下
  RESUME: null        # 是否从断点恢复
  VAL_PERIOD: 1       # 每训练1个epoch验证一次

MODEL:
  NAME: gaze_model        # 与 gaze_model.py 文件名一致
  TYPE: gaze_model
  PRETRAINED:
    PATH: null
  TRANSFORMER:
    FEATURE_DIM: 128
    LAYERS: 3
    HEADS: 4
    USE_HEADPOSE: true
  LOSS:
    TYPE: l2
  INIT:
    CONV:
      TYPE: kaiming_normal
    LINEAR:
      TYPE: xavier_normal
    BN:
      WEIGHT: 1
      BIAS: 0

OPTIMIZER:
  NAME: adam
  LR: 0.0001
  WEIGHT_DECAY: 0.0001
  ADAM:
    BETAS: [0.9, 0.999]
    EPS: 1e-08

SCHEDULER:
  NAME: cosine
  EPOCHS: 30
  COSINE:
    T_MAX: 30
    ETA_MIN: 0.00001

TRAIN:
  BATCH_SIZE: 64
  NUM_WORKERS: 4
  PIN_MEMORY: true
  SHUFFLE: true
  DROP_LAST: true
  BATCH_ACCUMULATION: 1

VAL:
  BATCH_SIZE: 256
  NUM_WORKERS: 4
  PIN_MEMORY: true
  USE_TEST_AS_VAL: false
  VAL_RATIO: 0.1
  VAL_INDICES: null

TEST:
  RUN_TEST: true

DEVICE:
  GPUS: 1
  PRECISION: 32
  ACCELERATOR: gpu
  SYNC_BN: false
  CUDNN:
    BENCHMARK: true
    DETERMINISTIC: false

LOG:
  SHOW_PROGRESS_BAR: true
  LOG_PERIOD: 50

  CHECKPOINT:
    FILENAME: '{epoch:04d}'
    PERIOD: 1
    SAVE_LAST: true
    VERBOSE: false

  USE_TENSORBOARD: true
  TENSORBOARD:
    LOG_DIR: tensorboard
    DEFAULT_HP_METRIC: false

  USE_WANDB: false
  WANDB:
    PROJECT: gaze-estimation
    RUN_ID: null
    GROUP: null

  USE_CONSOLE_LOGGER: true
  CONSOLE:
    SHOW_CONFIG: true
    STAGE_NAME_COLOR: cyan
    TRAIN_KEY_COLOR: green
    VAL_KEY_COLOR: yellow

DEBUG:
  FAST_DEV_RUN: false
  NUM_SANITY_VAL_STEPS: 0
  PROFILER: null
  WEIGHT_SUMMARY: null
